<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>url</string>
	</array>
	<key>name</key>
	<string>url</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>include</key>
			<string>#comments</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#constants</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#keywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#annokeywords</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#storagetypes</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#enum</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#packaging</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#rootclass</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#class</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#strings</string>
		</dict>
		<dict>
			<key>include</key>
			<string>#scriptblock</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>annokeywords</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@check|@model|@tips|@ep|@ctx|@caa)(\(*)</string>
		</dict>
		<key>class</key>
		<dict>
			<key>begin</key>
			<string>(class)\s+([A-Za-z][A-Za-z0-9-_]*)(,\s+namerequired)?\s+(extends\s+)?([A-Za-z][A-Za-z0-9-_]*)?(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.metaclass.url</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.supperclass.url</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>$self</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storagetypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
			</array>
		</dict>
		<key>comments</key>
		<dict>
			<key>patterns</key>
			<array>
				<dict>
					<key>begin</key>
					<string>/\*</string>
					<key>end</key>
					<string>\*/</string>
					<key>name</key>
					<string>comment.block.url</string>
				</dict>
				<dict>
					<key>begin</key>
					<string>//</string>
					<key>end</key>
					<string>$\n?</string>
					<key>name</key>
					<string>comment.line.double-slash.url</string>
				</dict>
			</array>
		</dict>
		<key>constants</key>
		<dict>
			<key>match</key>
			<string>\b(true|false|null)\b</string>
			<key>name</key>
			<string>constant.language.url</string>
		</dict>
		<key>enum</key>
		<dict>
			<key>begin</key>
			<string>(enum)\s*(Int|String)\s*([A-Za-z][A-Za-z0-9_]*)\s+(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.url</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.enum.url</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<dict>
					<key>captures</key>
					<dict>
						<key>1</key>
						<dict>
							<key>name</key>
							<string>constant.other.url</string>
						</dict>
						<key>5</key>
						<dict>
							<key>name</key>
							<string>constant.numeric.url</string>
						</dict>
					</dict>
					<key>match</key>
					<string>([A-Za-z][A-Za-z0-9_]\S+)(\s+)(=)(\s+)(["]?[A-Za-z0-9]["]?)(;)</string>
				</dict>
			</array>
		</dict>
		<key>keywords</key>
		<dict>
			<key>match</key>
			<string>\b(script|if|else|for|in|when|while|return|break|context)\b</string>
			<key>name</key>
			<string>keyword.source.url</string>
		</dict>
		<key>packaging</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>storage.type.url</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(package|import)((\s+)([A-Za-z][A-Za-z0-9-_.]*)(;))</string>
		</dict>
		<key>rootclass</key>
		<dict>
			<key>begin</key>
			<string>(root)\s+(class)\s+([A-Za-z][A-Za-z0-9-_]*)(,\s+namerequired)?\s+(extends\s+)?([A-Za-z][A-Za-z0-9-_]*)?(\{)?</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.rootclass.url</string>
				</dict>
				<key>4</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>5</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
				<key>6</key>
				<dict>
					<key>name</key>
					<string>entity.name.class.supperclass.url</string>
				</dict>
			</dict>
			<key>end</key>
			<string>\}</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#comments</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#constants</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#storagetypes</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#enum</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#class</string>
				</dict>
			</array>
		</dict>
		<key>scriptblock</key>
		<dict>
			<key>begin</key>
			<string>&lt;&lt;&lt;</string>
			<key>end</key>
			<string>&gt;&gt;&gt;</string>
			<key>name</key>
			<string>string.quoted.double.proto</string>
		</dict>
		<key>storagetypes</key>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>storage.type.url</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>keyword.source.url</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(String|Int|Long|Float|Double|Boolean|Number)\b\s+([A-Za-z][A-Za-z0-9_]*)?(,\s+required;)?</string>
		</dict>
		<key>strings</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.proto</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.url</string>
	<key>uuid</key>
	<string>65008556-31ff-426c-838a-6b7e79e4cc31</string>
</dict>
</plist>
